### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by 5ch03ffm4nn** [Peter92/MouseTracks#44]
Hello
I am completely excited about your project and would like to work with it. Unfortunately, I just can not get it to run. That's why I thought I'll ask the developer for help. 
I would be very happy if you would like to work together. 

I try to fix the problem on reddit but it does not work as well. https://redd.it/7vf5ud

That is what it looks like in the moment:
Launching a new console is not yet supported.
[02:57:31] Starting socket server... | Bound socket connection to port 52091. | Starting web server... | Bound web connection to port 52092. | The code required to connect to the message server is "63160f4b-0f53-459d-bdeb-56078c049de6".
[02:57:31] Set save location to "/Users/Mouse Tracks".
[02:57:31] Main process started.
[02:57:33] Background process started. | Finished loading data. | Unable to read cursor position.
[02:58:18] Background process quit. | Main process quit.

I hope you like to help me.

**Comment by Peter92** [comment]
Hey, thanks a bunch for the interest and attempting to get it running yourself. Despite what C-XD said about only using Python 3, I actually wrote this in Python 2 so occasionally bugs slip through the net, I've just gone and fixed a bunch if you want to try once more :)

Unfortunately though only Windows is fully supported currently, there's some very basic code for Mac (it can get mouse position, resolution, and loaded programs) but I'm relying on help for that as I don't actually own one myself :)

**Comment by 5ch03ffm4nn** [comment]
Ok thanks 
I already try it at Win10 but same problems. maybe you can help me out? 

I get:

 C:\Users\Desktop\MouseTracks-master>python start_tracking.py
PyWin32 import failed (reason: "DLL load failed: Das angegebene Modul wurde nicht gefunden."). Falling back to ctypes.
Traceback (most recent call last):
  File "start_tracking.py", line 11, in <module>
    import core.config
  File "C:\Users\Desktop\MouseTracks-master\core\__init__.py", line 9, in <module>
    import core.config
  File "C:\Users\Desktop\MouseTracks-master\core\config.py", line 829, in <module>
    CONFIG = Config(DEFAULTS).load(CONFIG_PATH).save()
  File "C:\Users\Desktop\MouseTracks-master\core\config.py", line 715, in init
    self._load_from_dict(defaults)
  File "C:\Users\Desktop\MouseTracks-master\core\config.py", line 735, in _load_from_dict
    for heading, var_data in iteritems(config_dict):
NameError: name 'iteritems' is not defined

You have a clue whats wrong?

**Comment by Peter92** [comment]
Hmm, that's really weird, did you re-download the full project after I made the fixes? Just have a quick check that line 12 in `core/config.py` is `from core.compatibility import iteritems`

**Comment by 5ch03ffm4nn** [comment]
ok i get it to run the start script.

PyWin32 import failed (reason: No module named 'win32api'). Falling back to ctypes.
[20:36:23] Starting socket server... | Bound socket connection to port 50007. | Starting web server... | Bound web connection to port 50008. | The code required to connect to the message server is "270c5a76-3c35-45d2-be2e-9d3165b1b460".
[20:36:23] Set save location to "C:/Users/Documents/Mouse Tracks".
[20:36:23] Main process started.
[20:36:23] 0 commands queued for processing.
[20:36:23] Finished reloading application list.
PyWin32 import failed (reason: No module named 'win32api'). Falling back to ctypes.
[20:36:24] Background process started.
[20:36:24] Finished loading data. | 26 commands queued for processing.
[20:36:26] Left mouse button clicked at (457, 416).
[20:36:46] Right mouse button clicked at (465, 254).

But if i start: generate_images.py i get no imeage.

Importing modules...
Loading profile vx7...
What do you want to generate?
Separate options with a space, or hit enter for the default of "1 4".
1: Tracks
2: Acceleration
3: Click Heatmap
4: Keyboard Heatmap (The keyboard doesn't appear to have been tracked for this application.)
5: CSV File
1
No tracking data found.
Opening image folder...

Process finished with exit code 0

**Comment by Peter92** [comment]
Currently there no validation if the profile exists or not (something I need to rewrite).

It looks like you typed "vx7" for the profile - it'll either be "Default" or the name of the game you were playing. If you type "list" it'll give you a choice :)

**Comment by 5ch03ffm4nn** [comment]
Thank you,  How can i make a new track pic? If i close the start.py and start image i always get the same pic.

**Comment by Peter92** [comment]
Do you mean it always looks the same, or you're trying it with different colours and it's being overwritten?

In the first case, you can edit the colours in the config. In the second case you can change how they're named (also in the config), by default it just uses the length of the tracking.

If you literally want to start over though, just delete the data folder in your documents. On my phone so I can't tell you the exact config parts, let me know if you're having trouble though.

Not sure about the upside down image though, are both tracks and clicks definitely the wrong way?
